### ISSUE TITLE
Ctrl-C is a possible UX-headache

### ISSUE THREAD

**Issue by gurkanctn** [L0huis/Whiteboard#1]
Ctrl-C is generally a shortcut for "copy" and, you may want to use Ctrl-C for a Copy operation, instead of a Clear operation.

Suggest changing the shortcut of Clear to sth else. (Ctrl-A + DEL ?)

**Comment by L0huis** [comment]
Good point but there is no Copy operation planned, so I'll just keep it as it is.
You can easily change it by yourself by changing Whiteboard.cpp:56:
```c++
if (!m_splines.empty() && evt.ControlDown() && evt.GetUnicodeKey() == 'C')
                                                                     //^~~ Change this to some other letter
```
